### ISSUE TITLE
Invantory for pokemon corruption

### ISSUE THREAD

**Issue by MrDrony8X8** [PocketSprite/8bkc-gnuboy#5]
In pokemon silver and gold gbc items and pokemon in the computer change to to different things or dissappear completely when the device is powered down.  There seems to be no way to open the rom to the pokemon home screen to load save within the game.

**Comment by Spritetm** [comment]
Hm, seems something is going wrong saving the upper pages of the SRAM. I'll look into it.

**Comment by Spritetm** [comment]
Should be fixed now. New binaries can be downloaded here: https://www.reddit.com/r/PocketSprite/comments/8uk80a/testers_wanted_beta_apps/

**Comment by Asara** [comment]
Would this also affect the save game itself?

I saved the game (pokemon red, a save game, not a save state), and reset the emulator.  On startup, the game said my save game was destroyed and I was forced to start a new game.

**Comment by Asara** [comment]
Well I tested the new version and it seems to fix my issue as well!

**Comment by MrDrony8X8** [comment]
Loving my pocketsprite and I have Updated everything. Red blue green yellow work perfectly but silver gold still can't save game or pokemon in the computer.

**Comment by MrDrony8X8** [comment]
Silver is saving now!! Thank you I am loving my Pocketsprite and all new features and fixes in the update. I'm halfway through yellow. If possible Donkey Kong Country is all fuzzy distorted. Thank you for you help.
